{
 "title": "PiHole",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "PiStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.stats",
     "select": [
      [
       { "params": [ "ads_blocked_today" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.querries",
     "select": [
      [
       { "params": [ "dns_queries_today" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unique Clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.state",
     "select": [
      [
       { "params": [ "unique_clients" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Clients Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.state",
     "select": [
      [
       { "params": [ "clients_ever_seen" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries Today",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Queries Today",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.querries",
     "select": [
      [
       { "params": [ "dns_queries_today" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ads Blocked Today (Percentage)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "Today blocked ads in percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.stats",
     "select": [
      [
       { "params": [ "ads_percentage_today" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Domains",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Unique Domains",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.querries",
     "select": [
      [
       { "params": [ "unique_domains" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Domains Blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Domains Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.state",
     "select": [
      [
       { "params": [ "domains_being_blocked" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ads Blocked Today",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Ads Blocked Today",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.stats",
     "select": [
      [
       { "params": [ "ads_blocked_today" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pihole.state",
     "query": "SELECT mean(\"status\") FROM \"piholestats.pihole\" WHERE (\"host\" = 'pihole') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "raspberrypi" }
     ]
    }
   ]
  },
  {
   "title": "Cached Domains",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Cached Domains",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.querries",
     "select": [
      [
       { "params": [ "queries_cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forwarded Domains",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "Forwarded Domains",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pihole.querries",
     "select": [
      [
       { "params": [ "queries_forwarded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}